# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parachute_console.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from ui_console.m4_QLabel import *
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 971)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/gyq_65.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setUnderline(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.m4_DeviceList = QtWidgets.QTreeView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m4_DeviceList.sizePolicy().hasHeightForWidth())
        self.m4_DeviceList.setSizePolicy(sizePolicy)
        self.m4_DeviceList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.m4_DeviceList.setObjectName("m4_DeviceList")
        self.verticalLayout.addWidget(self.m4_DeviceList)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 3, 1, 1)
        self.m4_ImageShow = m4_QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.m4_ImageShow.sizePolicy().hasHeightForWidth())
        self.m4_ImageShow.setSizePolicy(sizePolicy)
        self.m4_ImageShow.setFrameShape(QtWidgets.QFrame.Box)
        self.m4_ImageShow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.m4_ImageShow.setText("")
        self.m4_ImageShow.setPixmap(QtGui.QPixmap(":/pic/IfyEzBj.jpg"))
        self.m4_ImageShow.setScaledContents(True)
        self.m4_ImageShow.setObjectName("m4_ImageShow")
        self.gridLayout.addWidget(self.m4_ImageShow, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 1, 3, 1, 1)
        self.m4_ToolBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.m4_ToolBox.sizePolicy().hasHeightForWidth())
        self.m4_ToolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.m4_ToolBox.setFont(font)
        self.m4_ToolBox.setObjectName("m4_ToolBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.m4_ToolBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.m4_XSearch = QtWidgets.QLineEdit(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_XSearch.sizePolicy().hasHeightForWidth())
        self.m4_XSearch.setSizePolicy(sizePolicy)
        self.m4_XSearch.setObjectName("m4_XSearch")
        self.gridLayout_2.addWidget(self.m4_XSearch, 8, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.m4_ToolBox)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 4, 0, 1, 3)
        self.m4_YStep = QtWidgets.QLineEdit(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_YStep.sizePolicy().hasHeightForWidth())
        self.m4_YStep.setSizePolicy(sizePolicy)
        self.m4_YStep.setObjectName("m4_YStep")
        self.gridLayout_2.addWidget(self.m4_YStep, 10, 2, 1, 1)
        self.m4_XStep = QtWidgets.QLineEdit(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_XStep.sizePolicy().hasHeightForWidth())
        self.m4_XStep.setSizePolicy(sizePolicy)
        self.m4_XStep.setObjectName("m4_XStep")
        self.gridLayout_2.addWidget(self.m4_XStep, 10, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.m4_ToolBox)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 11, 0, 1, 3)
        self.m4_ManualModel = QtWidgets.QRadioButton(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_ManualModel.sizePolicy().hasHeightForWidth())
        self.m4_ManualModel.setSizePolicy(sizePolicy)
        self.m4_ManualModel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/ma.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m4_ManualModel.setIcon(icon1)
        self.m4_ManualModel.setIconSize(QtCore.QSize(40, 40))
        self.m4_ManualModel.setChecked(True)
        self.m4_ManualModel.setObjectName("m4_ManualModel")
        self.gridLayout_2.addWidget(self.m4_ManualModel, 3, 1, 1, 1)
        self.m4_YSearch = QtWidgets.QLineEdit(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_YSearch.sizePolicy().hasHeightForWidth())
        self.m4_YSearch.setSizePolicy(sizePolicy)
        self.m4_YSearch.setObjectName("m4_YSearch")
        self.gridLayout_2.addWidget(self.m4_YSearch, 8, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.m4_DetectImageShow = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.m4_DetectImageShow.sizePolicy().hasHeightForWidth())
        self.m4_DetectImageShow.setSizePolicy(sizePolicy)
        self.m4_DetectImageShow.setMinimumSize(QtCore.QSize(240, 240))
        self.m4_DetectImageShow.setMaximumSize(QtCore.QSize(1000000, 240))
        self.m4_DetectImageShow.setFrameShape(QtWidgets.QFrame.Box)
        self.m4_DetectImageShow.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.m4_DetectImageShow.setText("")
        self.m4_DetectImageShow.setPixmap(QtGui.QPixmap(":/pic/para.png"))
        self.m4_DetectImageShow.setScaledContents(True)
        self.m4_DetectImageShow.setObjectName("m4_DetectImageShow")
        self.gridLayout_2.addWidget(self.m4_DetectImageShow, 15, 0, 1, 3)
        self.line_6 = QtWidgets.QFrame(self.m4_ToolBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 14, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 12, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 9, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 9, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 7, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 12, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.m4_ToolBox)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 2, 0, 1, 3)
        self.m4_AutoModel = QtWidgets.QRadioButton(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_AutoModel.sizePolicy().hasHeightForWidth())
        self.m4_AutoModel.setSizePolicy(sizePolicy)
        self.m4_AutoModel.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/resizeApi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m4_AutoModel.setIcon(icon2)
        self.m4_AutoModel.setIconSize(QtCore.QSize(40, 40))
        self.m4_AutoModel.setObjectName("m4_AutoModel")
        self.gridLayout_2.addWidget(self.m4_AutoModel, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.m4_FocalLength = QtWidgets.QLineEdit(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m4_FocalLength.sizePolicy().hasHeightForWidth())
        self.m4_FocalLength.setSizePolicy(sizePolicy)
        self.m4_FocalLength.setObjectName("m4_FocalLength")
        self.gridLayout_2.addWidget(self.m4_FocalLength, 1, 1, 1, 1)
        self.m4_YoloNms = QtWidgets.QLineEdit(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_YoloNms.sizePolicy().hasHeightForWidth())
        self.m4_YoloNms.setSizePolicy(sizePolicy)
        self.m4_YoloNms.setObjectName("m4_YoloNms")
        self.gridLayout_2.addWidget(self.m4_YoloNms, 13, 2, 1, 1)
        self.m4_YoloScore = QtWidgets.QLineEdit(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_YoloScore.sizePolicy().hasHeightForWidth())
        self.m4_YoloScore.setSizePolicy(sizePolicy)
        self.m4_YoloScore.setObjectName("m4_YoloScore")
        self.gridLayout_2.addWidget(self.m4_YoloScore, 13, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.m4_ToolBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 6, 0, 1, 3)
        self.label_12 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.m4_ToolBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 12, 0, 2, 1)
        self.label_9 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 7, 0, 4, 1)
        self.label_8 = QtWidgets.QLabel(self.m4_ToolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 1, 1, 2)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.m4_ToolBox, 0, 4, 1, 1)
        self.m4_State = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.m4_State.sizePolicy().hasHeightForWidth())
        self.m4_State.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.m4_State.setFont(font)
        self.m4_State.setObjectName("m4_State")
        self.gridLayout.addWidget(self.m4_State, 2, 2, 1, 1)
        self.m4_Remainder = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_Remainder.sizePolicy().hasHeightForWidth())
        self.m4_Remainder.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.m4_Remainder.setFont(font)
        self.m4_Remainder.setObjectName("m4_Remainder")
        self.gridLayout.addWidget(self.m4_Remainder, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 4, 1, 1)
        self.m4_OutputState = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.m4_OutputState.sizePolicy().hasHeightForWidth())
        self.m4_OutputState.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.m4_OutputState.setFont(font)
        self.m4_OutputState.setObjectName("m4_OutputState")
        self.gridLayout.addWidget(self.m4_OutputState, 2, 0, 1, 1)
        self.m4_OutputRemainder = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.m4_OutputRemainder.sizePolicy().hasHeightForWidth())
        self.m4_OutputRemainder.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        self.m4_OutputRemainder.setFont(font)
        self.m4_OutputRemainder.setObjectName("m4_OutputRemainder")
        self.gridLayout.addWidget(self.m4_OutputRemainder, 3, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 2, 1, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 3, 1, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 2, 3, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 3, 3, 1, 1)
        self.m4_OutputInfo = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.m4_OutputInfo.setFont(font)
        self.m4_OutputInfo.setObjectName("m4_OutputInfo")
        self.gridLayout.addWidget(self.m4_OutputInfo, 2, 4, 2, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.m4_Yanhua_action = QtWidgets.QAction(MainWindow)
        self.m4_Yanhua_action.setObjectName("m4_Yanhua_action")
        self.m4_BeckHoff_action = QtWidgets.QAction(MainWindow)
        self.m4_BeckHoff_action.setObjectName("m4_BeckHoff_action")
        self.m4_manual_tracking_action = QtWidgets.QAction(MainWindow)
        self.m4_manual_tracking_action.setObjectName("m4_manual_tracking_action")
        self.m4_start_tracking_action = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/track_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m4_start_tracking_action.setIcon(icon3)
        self.m4_start_tracking_action.setObjectName("m4_start_tracking_action")
        self.m4_power_on_action = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/1138396.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m4_power_on_action.setIcon(icon4)
        self.m4_power_on_action.setObjectName("m4_power_on_action")
        self.m4_power_down_action = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pic/rdfs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m4_power_down_action.setIcon(icon5)
        self.m4_power_down_action.setObjectName("m4_power_down_action")
        self.m4_open_camera_action = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pic/opencamera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m4_open_camera_action.setIcon(icon6)
        self.m4_open_camera_action.setObjectName("m4_open_camera_action")
        self.m4_close_camera_action = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/pic/closecamera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.m4_close_camera_action.setIcon(icon7)
        self.m4_close_camera_action.setObjectName("m4_close_camera_action")
        self.menu.addAction(self.m4_open_camera_action)
        self.menu.addAction(self.m4_close_camera_action)
        self.menu.addAction(self.m4_power_on_action)
        self.menu.addAction(self.m4_power_down_action)
        self.menu.addAction(self.m4_start_tracking_action)
        self.menu_2.addAction(self.m4_Yanhua_action)
        self.menu_2.addAction(self.m4_BeckHoff_action)
        self.menu_2.addAction(self.m4_manual_tracking_action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.m4_open_camera_action)
        self.toolBar.addAction(self.m4_close_camera_action)
        self.toolBar.addAction(self.m4_power_on_action)
        self.toolBar.addAction(self.m4_power_down_action)
        self.toolBar.addAction(self.m4_start_tracking_action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parachute Tracking Console"))
        self.label.setText(_translate("MainWindow", "设备参数："))
        self.groupBox.setTitle(_translate("MainWindow", "设备列表"))
        self.label_2.setText(_translate("MainWindow", "设备状态："))
        self.m4_ToolBox.setTitle(_translate("MainWindow", "工具箱"))
        self.label_7.setText(_translate("MainWindow", "参数"))
        self.label_6.setText(_translate("MainWindow", "手|自动"))
        self.label_3.setText(_translate("MainWindow", "焦距："))
        self.label_17.setText(_translate("MainWindow", "nms："))
        self.label_15.setText(_translate("MainWindow", "y-step"))
        self.label_14.setText(_translate("MainWindow", "x-step"))
        self.label_13.setText(_translate("MainWindow", "y-search:"))
        self.label_16.setText(_translate("MainWindow", "score："))
        self.label_4.setText(_translate("MainWindow", "mm"))
        self.m4_FocalLength.setText(_translate("MainWindow", "50"))
        self.label_12.setText(_translate("MainWindow", "x-search:"))
        self.label_11.setText(_translate("MainWindow", "检测："))
        self.label_9.setText(_translate("MainWindow", "跟踪："))
        self.label_8.setText(_translate("MainWindow", "值："))
        self.label_5.setText(_translate("MainWindow", "输出信息："))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "调试界面"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.m4_Yanhua_action.setText(_translate("MainWindow", "研华板卡调试界面"))
        self.m4_BeckHoff_action.setText(_translate("MainWindow", "倍福控制器调试界面"))
        self.m4_manual_tracking_action.setText(_translate("MainWindow", "手动跟踪调试界面"))
        self.m4_start_tracking_action.setText(_translate("MainWindow", "开始跟踪"))
        self.m4_power_on_action.setText(_translate("MainWindow", "电机上电"))
        self.m4_power_on_action.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">电机上电</span></p></body></html>"))
        self.m4_power_down_action.setText(_translate("MainWindow", "电机断电"))
        self.m4_open_camera_action.setText(_translate("MainWindow", "打开相机"))
        self.m4_open_camera_action.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.m4_close_camera_action.setText(_translate("MainWindow", "关闭相机"))

import apprcc_rc
